//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 14.11.2017 19:48:42
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace abdModel
{
    public enum Przestępstwo : int
    {

        Folgowanie,    
        Kradzież,    
        Zabójstwo
    }
}
